const elementaryWords = [
{en:"a (an)",zh:"一(個)"}, 
{en:"a few",zh:"一些"},
{en:"a little",zh:"一些"}, 
{en:"a lot",zh:"許多"},
{en:"able",zh:"能夠...的"}, 
{en:"about",zh:"關於"}, 
{en:"above",zh:"在...上方"}, 
{en:"abroad",zh:"在國外"}, 
{en:"across",zh:"在...對面"}, 
{en:"actress",zh:"女演員"}, 
{en:"afraid",zh:"害怕的"},
{en:"after",zh:"在...之後"},
{en:"afternoon",zh:"下午"}, 
{en:"again",zh:"再一次"}, 
{en:"age",zh:"年齡"},
{en:"ago",zh:"以前"},
{en:"agree",zh:"同意"}, 
{en:"ahead",zh:"在前方"},
{en:"air",zh:"空氣"},
{en:"airplane",zh:"飛機"}, 
{en:"airport",zh:"機場"}, 
{en:"all",zh:"全部的"}, 
{en:"almost",zh:"幾乎"}, 
{en:"along",zh:"沿著"}, [cite: 34]
{en:"already",zh:"已經"}, [cite: 34]
{en:"also",zh:"也"}, [cite: 34]
{en:"always",zh:"總是"}, [cite: 34]
{en:"a.m.",zh:"上午"}, [cite: 34]
{en:"America",zh:"美國"}, [cite: 34]
{en:"American",zh:"美國人:美國的"}, [cite: 34]
{en:"and",zh:"和"}, [cite: 34]
{en:"angry",zh:"生氣的"}, [cite: 34]
{en:"animal",zh:"動物"}, [cite: 34]
{en:"another",zh:"另一個的"}, [cite: 34]
{en:"answer",zh:"回答"}, [cite: 34]
{en:"ant",zh:"螞蟻"}, [cite: 34]
{en:"any",zh:"任何的"}, [cite: 34]
{en:"anyone",zh:"任何人"}, [cite: 34]
{en:"anything",zh:"任何事物"}, [cite: 34]
{en:"apartment",zh:"公寓"}, [cite: 34]
{en:"appear",zh:"出現"}, [cite: 34]
{en:"apple",zh:"蘋果"}, [cite: 34]
{en:"April",zh:"四月"}, [cite: 34]
{en:"arm",zh:"手臂,武裝"}, [cite: 34]
{en:"around",zh:"在...四周"}, [cite: 34]
{en:"arrive",zh:"到達"}, [cite: 34]
{en:"art",zh:"美術"}, [cite: 34]
{en:"as",zh:"與...一樣"}, [cite: 34]
{en:"ask",zh:"問"}, [cite: 34]
{en:"at",zh:"在"}, [cite: 34]
{en:"August",zh:"八月"}, [cite: 34]
{en:"aunt",zh:"伯(叔)母"}, [cite: 34]
{en:"autumn",zh:"秋天"}, [cite: 34]
{en:"away",zh:"遠離"}, [cite: 34]
{en:"baby",zh:"嬰兒"}, [cite: 34]
{en:"back",zh:"在...後面"}, [cite: 34]
{en:"bad",zh:"壞的"}, [cite: 34]
{en:"badminton",zh:"羽毛球"}, [cite: 34]
{en:"bag",zh:"袋子"}, [cite: 34]
{en:"bake",zh:"烘烤"}, [cite: 34]
{en:"bakery",zh:"麵包店"}, [cite: 34]
{en:"balcony",zh:"陽台"}, [cite: 34]
{en:"ball",zh:"球"}, [cite: 34]
{en:"banana",zh:"香蕉"}, [cite: 34]
{en:"band",zh:"樂團"}, [cite: 34]
{en:"bank",zh:"銀行"}, [cite: 34]
{en:"barbecue",zh:"烤肉"}, [cite: 34]
{en:"baseball",zh:"棒球"}, [cite: 34]
{en:"basket",zh:"籃子"}, [cite: 34]
{en:"basketball",zh:"籃球"}, 
{en:"bat",zh:"蝙蝠"}
{en:"bath",zh:"洗澡"}
{en:"bathroom",zh:"浴室"}
{en:"be",zh:"是"}
{en:"beach",zh:"海灘"}
{en:"bean",zh:"豆"}
{en:"bear",zh:"熊"}
{en:"beautiful",zh:"美麗的"}
{en:"because",zh:"因為"}
{en:"become",zh:"變成"}
{en:"bed",zh:"床"}
{en:"bedroom",zh:"臥室"}
{en:"bee",zh:"蜜蜂"}
{en:"beef",zh:"牛肉"}
{en:"before",zh:"在...之前"}
{en:"begin",zh:"開始"}
{en:"behind",zh:"在...後面"}
{en:"believe",zh:"相信"}
{en:"bell",zh:"鈴"}
{en:"belong",zh:"屬於"}
{en:"below",zh:"在...下方"}
{en:"belt",zh:"皮帶"}
{en:"bench",zh:"長椅"}
{en:"beside",zh:"在...旁邊"}
{en:"between",zh:"在...之間"}
{en:"bike",zh:"腳踏車"}
{en:"big",zh:"大的"}
{en:"bird",zh:"鳥"}
{en:"birthday",zh:"生日"}
{en:"bite",zh:"咬"}
{en:"black",zh:"黑色(的)"}
{en:"blackboard",zh:"黑板"}
{en:"blanket",zh:"毯子"}
{en:"blind",zh:"瞎的"}
{en:"block",zh:"街區"}
{en:"blow",zh:"吹"}
{en:"blue",zh:"藍色(的)"}
{en:"boat",zh:"船"}
{en:"body",zh:"身體"}
{en:"boil",zh:"煮沸"}
{en:"book",zh:"書"}
{en:"bookstore",zh:"書店"}
{en:"bored",zh:"感到厭煩的"}
{en:"boring",zh:"無聊的"}
{en:"born",zh:"出生"}
{en:"borrow",zh:"借入"}
{en:"boss",zh:"老板"}
{en:"both",zh:"兩者都"}
{en:"bottle",zh:"瓶子"}
{en:"bottom",zh:"底部"}
{en:"bow",zh:"敬禮"}
{en:"bowl",zh:"碗"}
{en:"box",zh:"盒子"}
{en:"boy",zh:"男孩"}
{en:"bread",zh:"麵包"}
{en:"break",zh:"打破"}
{en:"breakfast",zh:"早餐"}
{en:"bridge",zh:"橋"}
{en:"bright",zh:"明亮的"}
{en:"bring",zh:"帶來"}
{en:"brother",zh:"兄弟"}
{en:"brown",zh:"棕色(的)"}
{en:"brush",zh:"刷"}
{en:"bug",zh:"小蟲"}
{en:"build",zh:"建造"}
{en:"bun",zh:"小圓麵包"}
{en:"burn",zh:"燃燒"}
{en:"bus",zh:"公車"}
{en:"business",zh:"生意"}
{en:"businessman",zh:"商人"}
{en:"busy",zh:"忙碌的"}
{en:"but",zh:"但是"}
{en:"butter",zh:"奶油"}
{en:"butterfly",zh:"蝴蝶"}
{en:"buy",zh:"買"}
{en:"by",zh:"藉著"}
{en:"cage",zh:"籠子"}
{en:"cake",zh:"蛋糕"}
{en:"call",zh:"打電話"}
{en:"cap",zh:"(無邊)帽"}
{en:"camp",zh:"露營"}
{en:"can",zh:"能夠"}
{en:"candle",zh:"蠟燭"}
{en:"candy",zh:"糖果"}
{en:"camera",zh:"照相機"}
{en:"car",zh:"車子"}
{en:"card",zh:"卡片"}
{en:"care",zh:"關心"}
{en:"careful",zh:"仔細的"}
{en:"carry",zh:"攜帶"}
{en:"case",zh:"情形"}
{en:"castle",zh:"城堡"}
{en:"cat",zh:"貓"}
{en:"catch",zh:"趕上"}
{en:"celebrate",zh:"慶祝"}
{en:"cell phone",zh:"手機"}
{en:"cent",zh:"〈一〉分錢"}
{en:"center",zh:"中心"}
{en:"centimeter",zh:"公分"}
{en:"chair",zh:"椅子"}
{en:"chalk",zh:"粉筆"}
{en:"chance",zh:"機會"}
{en:"change",zh:"交換,零錢"}
{en:"cheap",zh:"便宜的"}
{en:"cheat",zh:"欺騙"}
{en:"check",zh:"檢查"}
{en:"cheer",zh:"歡呼"}
{en:"cheese",zh:"乳酪"}
{en:"chess",zh:"西洋棋"}
{en:"chicken",zh:"雞肉"}
{en:"child",zh:"小孩"}
{en:"China",zh:"中國"}
{en:"Chinese",zh:"中國人,中文"}
{en:"chocolate",zh:"巧克力"}
{en:"choose",zh:"選擇"}
{en:"chopsticks",zh:"筷子"}
{en:"Christmas",zh:"聖誕節"}
{en:"church",zh:"教堂"}
{en:"circle",zh:"圓圈"}
{en:"city",zh:"城市"}
{en:"clap",zh:"拍手"}
{en:"class",zh:"班級"}
{en:"classmate",zh:"同班同學"}
{en:"classroom",zh:"教室"}
{en:"clean",zh:"打掃"}
{en:"clear",zh:"清楚的"}
{en:"clerk",zh:"店員"}
{en:"climb",zh:"爬"}
{en:"clock",zh:"時鐘"}
{en:"close",zh:"關上"}
{en:"clothes",zh:"衣服"}
{en:"cloudy",zh:"多雲的"}
{en:"club",zh:"社團"}
{en:"coat",zh:"大衣"}
{en:"coffee",zh:"咖啡"}
{en:"Coke",zh:"可樂"}
{en:"cold",zh:"寒冷的"}
{en:"collect",zh:"收集"}
{en:"color",zh:"顏色"}
{en:"come",zh:"來"}
{en:"comb",zh:"梳子"}
{en:"comfortable",zh:"舒適的"}
{en:"comic",zh:"連環漫畫"}
{en:"common",zh:"共同的"}
{en:"computer",zh:"電腦"}
{en:"convenient",zh:"方便的"}
{en:"cook",zh:"煮飯"}
{en:"cookie",zh:"餅乾"}
{en:"cool",zh:"涼爽的"}
{en:"copy",zh:"抄寫,複製"}
{en:"corner",zh:"角落"}
{en:"correct",zh:"正確的"}
{en:"cost",zh:"價值"}
{en:"couch",zh:"沙發"}
{en:"count",zh:"計算"}
{en:"country",zh:"鄉村"}
{en:"course",zh:"課程"}
{en:"cousin",zh:"堂,表兄弟姊妹"}
{en:"cover",zh:"覆蓋,封面,掩護"}
{en:"cow",zh:"母牛"}
{en:"cowboy",zh:"牛仔"}
{en:"crazy",zh:"瘋狂的"}
{en:"cross",zh:"越過"}
{en:"cry",zh:"哭"}
{en:"cup",zh:"茶杯"}
{en:"cut",zh:"切"}
{en:"cute",zh:"可愛的"}
{en:"dance",zh:"跳舞"}
{en:"dangerous",zh:"危險的"}
{en:"dark",zh:"黑暗的"}
{en:"date",zh:"日期"}
{en:"daughter",zh:"女兒"}
{en:"day",zh:"日子"}
{en:"dead",zh:"死的"}
{en:"dear",zh:"親愛的"}
{en:"December",zh:"十二月"}
{en:"decide",zh:"決定"}
{en:"delicious",zh:"美味的"}
{en:"dentist",zh:"牙醫"}
{en:"department store",zh:"百貨公司"}
{en:"desk",zh:"書桌"}
{en:"dictionary",zh:"字典"}
{en:"die",zh:"死掉"}
{en:"different",zh:"不同的"}
{en:"difficult",zh:"困難的"}
{en:"dig",zh:"挖掘"}
{en:"dining room",zh:"飯廳"}
{en:"dinner",zh:"晚餐"}
{en:"dirty",zh:"骯髒的"}
{en:"dish",zh:"盤子,菜餚"}
{en:"do",zh:"做"}
{en:"doctor",zh:"醫生"}
{en:"dodge ball",zh:"躲避球"}
{en:"dog",zh:"狗"}
{en:"doll",zh:"洋娃娃"}
{en:"dollar",zh:"元"}
{en:"door",zh:"門"}
{en:"dot",zh:"點"}
{en:"down",zh:"向下"}
{en:"dozen",zh:"〈一〉打"}
{en:"dragon",zh:"龍"}
{en:"draw",zh:"畫"}
{en:"drawer",zh:"抽屜"}
{en:"dream",zh:"(做)夢"}
{en:"dress",zh:"洋裝"}
{en:"drink",zh:"喝"}
{en:"drive",zh:"駕駛"}
{en:"driver",zh:"駕駛人"}
{en:"drop",zh:"掉落"}
{en:"drum",zh:"鼓"}
{en:"dry",zh:"乾的"}
{en:"duck",zh:"鴨"}
{en:"dumpling",zh:"包餡食物,餃子"}
{en:"during",zh:"在...期間"}
{en:"each",zh:"每一(的〉"}
{en:"ear",zh:"耳朵"}
{en:"early",zh:"早的"}
{en:"earth",zh:"地球"}
{en:"east",zh:"東方"}
{en:"Easter",zh:"復活節"}
{en:"easy",zh:"容易的"}
{en:"eat",zh:"吃"}
{en:"egg",zh:"蛋"}
{en:"eight",zh:"八"}
{en:"eighteen",zh:"十八"}
{en:"eighth",zh:"第八"}
{en:"eighty",zh:"八十"}
{en:"either",zh:"也不"}
{en:"elementary school",zh:"小學"}
{en:"elephant",zh:"大象"}
{en:"eleven",zh:"十一"}
{en:"eleventh",zh:"第十一(的)"}
{en:"else",zh:"其他的"}
{en:"e-mail",zh:"電子郵件"}
{en:"end",zh:"結束"}
{en:"engineer",zh:"工程師"}
{en:"English",zh:"英語"}
{en:"enjoy",zh:"喜愛"}
{en:"enough",zh:"足夠的"}
{en:"enter",zh:"進入"}
{en:"envelope",zh:"信"}
{en:"eraser",zh:"橡皮擦"}
{en:"eve",zh:"前夕"}
{en:"even",zh:"甚至"}
{en:"evening",zh:"傍晚"}
{en:"ever",zh:"曾經"}
{en:"every",zh:"每一個(的)"}
{en:"everyone",zh:"每一個人"}
{en:"everything",zh:"每件事"}
{en:"example",zh:"例子"}
{en:"excellent",zh:"極好的"}
{en:"except",zh:"除了...之外"}
{en:"excited",zh:"感到興奮的"}
{en:"exciting",zh:"令人興奮的"}
{en:"excuse",zh:"原諒"}
{en:"exercise",zh:"運動"}
{en:"expensive",zh:"昂貴的"}
{en:"experience",zh:"經驗"}
{en:"eye",zh:"眼睛"}
{en:"face",zh:"臉孔,面對"}
{en:"fact",zh:"事實"}
{en:"factory",zh:"工廠"}
{en:"fail",zh:"失敗"}
{en:"fall",zh:"秋天"}
{en:"family",zh:"家庭"}
{en:"famous",zh:"有名的"}
{en:"fan",zh:"扇子,擁護者"}
{en:"far",zh:"遠的"}
{en:"farm",zh:"農田"}
{en:"farmer",zh:"農夫"}
{en:"fast",zh:"快的"}
{en:"fat",zh:"胖的"}
{en:"father",zh:"父親"}
{en:"favorite",zh:"最喜愛的"}
{en:"February",zh:"二月"}
{en:"feed",zh:"餵"}
{en:"feel",zh:"覺得"}
{en:"festival",zh:"節慶"}
{en:"fever",zh:"發燒"}
{en:"few",zh:"少數的"}
{en:"fifteen",zh:"十五"}
{en:"fifteenth",zh:"第十五(的)"}
{en:"fifth",zh:"第五(的)"}
{en:"fifty",zh:"五十"}
{en:"fight",zh:"打架"}
{en:"fill",zh:"裝滿"}
{en:"finally",zh:"最後"}
{en:"find",zh:"找到"}
{en:"fine",zh:"很好的"}
{en:"finger",zh:"手指"}
{en:"finish",zh:"完成"}
{en:"fire",zh:"火焰,開火"}
{en:"first",zh:"第一(的)"}
{en:"fish",zh:"魚"}
{en:"fisherman",zh:"漁夫"}
{en:"five",zh:"五"}
{en:"fix",zh:"修理"}
{en:"floor",zh:"地板"}
{en:"flower",zh:"花朵"}
{en:"flute",zh:"笛"}
{en:"fly",zh:"飛"}
{en:"follow",zh:"遵循,跟隨"}
{en:"food",zh:"食物"}
{en:"foot",zh:"腳"}
{en:"for",zh:"為了"}
{en:"foreign",zh:"外國的"}
{en:"foreigner",zh:"外國人"}
{en:"forget",zh:"忘記"}
{en:"fork",zh:"叉子"}
{en:"forty",zh:"四十"}
{en:"four",zh:"四"}
{en:"fourteen",zh:"十四"}
{en:"fourteenth",zh:"第十四(的)"}
{en:"fourth",zh:"第四(的)"}
{en:"fox",zh:"狐狸"}
{en:"free",zh:"空閒的,免費"}
{en:"French fries",zh:"炸薯條"}
{en:"fresh",zh:"新鮮的"}
{en:"Friday",zh:"星期五"}
{en:"friend",zh:"朋友"}
{en:"friendly",zh:"友善的"}
{en:"frisbee",zh:"飛盤"}
{en:"frog",zh:"青蛙"}
{en:"from",zh:"從"}
{en:"front",zh:"前面"}
{en:"fruit",zh:"水果"}
{en:"fry",zh:"油炸"}
{en:"full",zh:"滿的"}
{en:"fun",zh:"樂趣"}
{en:"funny",zh:"好笑的"}
{en:"future",zh:"未來"}
{en:"game",zh:"比賽,遊戲"}
{en:"garbage",zh:"垃圾"}
{en:"garden",zh:"花園"}
{en:"gas",zh:"瓦斯"}
{en:"gate",zh:"大門"}
{en:"get",zh:"得到"}
{en:"ghost",zh:"鬼"}
{en:"giant",zh:"巨大的,巨人"}
{en:"gift",zh:"禮物"}
{en:"girl",zh:"女孩"}
{en:"give",zh:"給予"}
{en:"glad",zh:"高興的"}
{en:"glass",zh:"玻璃,玻璃杯"}
{en:"glasses",zh:"眼鏡"}
{en:"glove",zh:"手套"}
{en:"glue",zh:"膠水"}
{en:"go",zh:"去"}
{en:"goat",zh:"山羊"}
{en:"good",zh:"好的"}
{en:"goodbye",zh:"再見"}
{en:"goose",zh:"鵝"}
{en:"grade",zh:"成績,年級"}
{en:"gram",zh:"公克"}
{en:"grandfather",zh:"祖父"}
{en:"grandmother",zh:"祖母"}
{en:"grape",zh:"葡萄"}
{en:"grass",zh:"草"}
{en:"gray",zh:"灰色的"}
{en:"great",zh:"很棒的"}
{en:"green",zh:"綠色(的)"}
{en:"ground",zh:"地面"}
{en:"group",zh:"團體"}
{en:"grow",zh:"種植"}
{en:"guava",zh:"番石榴"}
{en:"guess",zh:"猜想"}
{en:"guitar",zh:"吉他"}
{en:"guy",zh:"傢伙"}
{en:"gym",zh:"體育館"}
{en:"habit",zh:"習慣"}
{en:"hair",zh:"頭髮"}
{en:"half",zh:"一半"}
{en:"Halloween",zh:"萬聖節"}
{en:"ham",zh:"火腿"}
{en:"hamburger",zh:"漢堡"}
{en:"hand",zh:"手"}
{en:"handsome",zh:"英俊的"}
{en:"hang",zh:"懸掛"}
{en:"happen",zh:"發生"}
{en:"happy",zh:"快樂的"}
{en:"hard",zh:"困難的,硬的"}
{en:"hard-working",zh:"努力工作的"}
{en:"hat",zh:"帽子"}
{en:"hate",zh:"討厭"}
{en:"have",zh:"有"}
{en:"he",zh:"他"}
{en:"head",zh:"頭"}
{en:"headache",zh:"頭痛"}
{en:"health",zh:"健康"}
{en:"healthy",zh:"健康的"}
{en:"hear",zh:"聽"}
{en:"heart",zh:"心"}
{en:"heat",zh:"熱度,加熱"}
{en:"heavy",zh:"重的"}
{en:"hello",zh:"喂"}
{en:"help",zh:"幫忙"}
{en:"helpful",zh:"有幫助的"}
{en:"hen",zh:"母雞"}
{en:"here",zh:"這裡"}
{en:"hey",zh:"哩"}
{en:"hi",zh:"嗨"}
{en:"hide",zh:"隱藏"}
{en:"high",zh:"高的"}
{en:"hike",zh:"徒步旅行"}
{en:"hill",zh:"小山"}
{en:"hippo",zh:"河馬"}
{en:"history",zh:"歷史"}
{en:"hit",zh:"打擊"}
{en:"hobby",zh:"嗜好"}
{en:"hold",zh:"拿著"}
{en:"holiday",zh:"假日"}
{en:"home",zh:"家"}
{en:"homework",zh:"家庭作業"}
{en:"honest",zh:"誠實的"}
{en:"honey",zh:"蜂蜜"}
{en:"hop",zh:"(單腳)跳"}
{en:"hope",zh:"希望"}
{en:"horse",zh:"馬"}
{en:"hospital",zh:"醫院"}
{en:"hot",zh:"熱的"}
{en:"hot dog",zh:"熱狗"}
{en:"hotel",zh:"旅社"}
{en:"hour",zh:"小時"}
{en:"house",zh:"房屋"}
{en:"housewife",zh:"家庭主婦"}
{en:"how",zh:"如何"}
{en:"however",zh:"然而"}
{en:"hundred",zh:"百"}
{en:"hungry",zh:"飢餓的"}
{en:"hunt",zh:"打獵"}
{en:"hurry",zh:"趕忙"}
{en:"hurt",zh:"受傷,疼痛"}
{en:"husband",zh:"丈夫"}
{en:"I",zh:"我"}
{en:"ice",zh:"冰"}
{en:"ice cream",zh:"冰淇淋"}
{en:"idea",zh:"主意"}
{en:"if",zh:"如果"}
{en:"important",zh:"重要的"}
{en:"in",zh:"在...裡面"}
{en:"insect",zh:"昆蟲"}
{en:"inside",zh:"在...內部"}
{en:"interest",zh:"使...感興趣"}
{en:"interested",zh:"感興趣的"}
{en:"interesting",zh:"有趣的"}
{en:"interview",zh:"訪問,面試"}
{en:"Internet",zh:"網路"}
{en:"into",zh:"到...之內"}
{en:"invite",zh:"邀請"}
{en:"island",zh:"島嶼"}
{en:"it",zh:"它"}
{en:"jacket",zh:"夾克"}
{en:"January",zh:"一月"}
{en:"jeans",zh:"牛仔褲"}
{en:"job",zh:"工作"}
{en:"jog",zh:"慢跑"}
{en:"join",zh:"加入"}
{en:"joy",zh:"歡樂"}
{en:"juice",zh:"果汁"}
{en:"July",zh:"七月"}
{en:"jump",zh:"跳躍"}
{en:"June",zh:"六月"}
{en:"junior high school",zh:"國中"}
{en:"just",zh:"只是,剛才"}
{en:"kangaroo",zh:"袋鼠"}
{en:"keep",zh:"保持"}
{en:"key",zh:"鑰匙"}
{en:"kick",zh:"踢"}
{en:"kid",zh:"小孩"}
{en:"kill",zh:"殺"}
{en:"kilo(gram)",zh:"公斤"}
{en:"kind",zh:"種類"}
{en:"king",zh:"國王"}
{en:"kiss",zh:"吻"}
{en:"kitchen",zh:"廚房"}
{en:"kite",zh:"風箏"}
{en:"knee",zh:"膝蓋"}
{en:"knife",zh:"刀子"}
{en:"knock",zh:"敲"}
{en:"know",zh:"知道"}
{en:"knowledge",zh:"知識"}
{en:"koala",zh:"無尾熊"}
{en:"lake",zh:"湖"}
{en:"lamp",zh:"燈"}
{en:"land",zh:"土地"}
{en:"language",zh:"語言"}
{en:"lantern",zh:"燈籠"}
{en:"large",zh:"大的"}
{en:"last",zh:"最後的"}
{en:"late",zh:"晚的"}
{en:"later",zh:"稍後"}
{en:"laugh",zh:"笑"}
{en:"lawyer",zh:"律師"}
{en:"lazy",zh:"懶惰的"}
{en:"lead",zh:"引導"}
{en:"leader",zh:"領導者"}
{en:"learn",zh:"學習"}
{en:"least",zh:"最少(的)"}
{en:"leave",zh:"離開"}
{en:"left",zh:"左邊"}
{en:"leg",zh:"腿"}
{en:"lemon",zh:"檸檬"}
{en:"lend",zh:"借出"}
{en:"less",zh:"較少的"}
{en:"lesson",zh:"課"}
{en:"let",zh:"讓"}
{en:"letter",zh:"信"}
{en:"lettuce",zh:"萵苣"}
{en:"library",zh:"圖書館"}
{en:"lid",zh:"蓋子"}
{en:"lie",zh:"說謊"}
{en:"life",zh:"生活"}
{en:"light",zh:"燈光,輕的"}
{en:"like",zh:"喜歡"}
{en:"line",zh:"隊伍,線條"}
{en:"lion",zh:"獅子"}
{en:"lip",zh:"嘴唇"}
{en:"list",zh:"表,名單"}
{en:"listen",zh:"聽"}
{en:"little",zh:"小的"}
{en:"live",zh:"住,活的,實況"}
{en:"living room",zh:"客廳"}
{en:"lonely",zh:"寂蹟的"}
{en:"long",zh:"長的"}
{en:"look",zh:"看"}
{en:"lose",zh:"遺失"}
{en:"loud",zh:"大聲的"}
{en:"love",zh:"喜愛"}
{en:"lovely",zh:"可愛的"}
{en:"low",zh:"低的"}
{en:"lucky",zh:"幸運的"}
{en:"lunch",zh:"午餐"}
{en:"machine",zh:"機器"}
{en:"mad",zh:"瘋狂的"}
{en:"magic",zh:"神奇的,魔術"}
{en:"mail",zh:"信件"}
{en:"mailman",zh:"郵差"}
{en:"make",zh:"製作"}
{en:"man",zh:"男人"}
{en:"many",zh:"許多的"}
{en:"map",zh:"地圖"}
{en:"March",zh:"三月"}
{en:"mark",zh:"做記號"}
{en:"marker",zh:"簽字筆"}
{en:"market",zh:"市場"}
{en:"married",zh:"已婚的"}
{en:"mask",zh:"面具"}
{en:"mat",zh:"墊子"}
{en:"math",zh:"數學"}
{en:"matter",zh:"事情"}
{en:"may",zh:"可能"}
{en:"May",zh:"五月"}
{en:"maybe",zh:"也許"}
{en:"meal",zh:"一餐"}
{en:"mean",zh:"意指"}
{en:"meat",zh:"肉"}
{en:"medicine",zh:"藥"}
{en:"medium",zh:"中號〈的〉"}
{en:"meet",zh:"遇見"}
{en:"meeting",zh:"會議"}
{en:"menu",zh:"菜單,選單"}
{en:"mile",zh:"英里,哩"}
{en:"milk",zh:"牛奶"}
{en:"million",zh:"百萬"}
{en:"mind",zh:"介意"}
{en:"minute",zh:"分鐘"}
{en:"Miss",zh:"小姐"}
{en:"miss",zh:"想念"}
{en:"mistake",zh:"錯誤"}
{en:"modern",zh:"現代化的"}
{en:"moment",zh:"片刻"}
{en:"Monday",zh:"星期一"}
{en:"money",zh:"錢"}
{en:"monkey",zh:"猴子"}
{en:"month",zh:"月份"}
{en:"moon",zh:"月亮"}
{en:"mop",zh:"拖地"}
{en:"more",zh:"更多的"}
{en:"morning",zh:"早上"}
{en:"most",zh:"大部分的"}
{en:"mother",zh:"母親"}
{en:"motorcycle",zh:"機車"}
{en:"mountain",zh:"山"}
{en:"mouse",zh:"老鼠"}
{en:"mouth",zh:"嘴巴"}
{en:"move",zh:"移動"}
{en:"movie",zh:"電影"}
{en:"Mr.",zh:"先生"}
{en:"Mrs.",zh:"太太"}
{en:"MRT",zh:"捷運"}
{en:"Ms.",zh:"女士"}
{en:"much",zh:"許多(不可數)"}
{en:"mud",zh:"泥巴"}
{en:"museum",zh:"博物館"}
{en:"music",zh:"音樂"}
{en:"must",zh:"必須"}
{en:"nail",zh:"釘子"}
{en:"name",zh:"名字"}
{en:"national",zh:"國家的"}
{en:"near",zh:"在...附近"}
{en:"neck",zh:"脖子"}
{en:"need",zh:"需要"}
{en:"neighbor",zh:"鄰居"}
{en:"never",zh:"從不"}
{en:"new",zh:"新的"}
{en:"news",zh:"消息,新聞"}
{en:"next",zh:"下一個"}
{en:"nice",zh:"好的"}
{en:"night",zh:"晚上"}
{en:"nine",zh:"九"}
{en:"nineteen",zh:"十九"}
{en:"nineteenth",zh:"第十九"}
{en:"ninety",zh:"九十"}
{en:"ninth",zh:"第九"}
{en:"no",zh:"沒有,不是"}
{en:"nobody",zh:"沒有人"}
{en:"nod",zh:"點頭"}
{en:"noise",zh:"噪音"}
{en:"noodle",zh:"麵條"}
{en:"noon",zh:"中午"}
{en:"north",zh:"北方"}
{en:"nose",zh:"鼻子"}
{en:"not",zh:"不,不是"}
{en:"note",zh:"筆記"}
{en:"notebook",zh:"筆記本,筆電"}
{en:"nothing",zh:"沒東西,沒事"}
{en:"notice",zh:"注意到"}
{en:"November",zh:"十一月"}
{en:"now",zh:"現在"}
{en:"number",zh:"號碼"}
{en:"nurse",zh:"護士"}
{en:"o'clock",zh:"點鐘"}
{en:"October",zh:"十月"}
{en:"of",zh:"...的"}
{en:"off",zh:"自...離開"}
{en:"office",zh:"辦公室"}
{en:"officer",zh:"官員"}
{en:"often",zh:"時常"}
{en:"oil",zh:"油"}
{en:"OK",zh:"可以"}
{en:"old",zh:"老的"}
{en:"on",zh:"在...上面"}
{en:"once",zh:"一次"}
{en:"one",zh:"一"}
{en:"only",zh:"只有"}
{en:"open",zh:"打開,開放"}
{en:"or",zh:"或"}
{en:"orange",zh:"柳橙"}
{en:"order",zh:"點餐,秩序"}
{en:"other",zh:"其他的"}
{en:"out",zh:"在外"}
{en:"outside",zh:"在...外部"}
{en:"over",zh:"結束"}
{en:"own",zh:"自己的"}
{en:"ox",zh:"公牛"}
{en:"pack",zh:"包"}
{en:"package",zh:"包裹"}
{en:"page",zh:"頁"}
{en:"paint",zh:"繪畫"}
{en:"pair",zh:"一雙"}
{en:"pants",zh:"長褲"}
{en:"papaya",zh:"木瓜"}
{en:"paper",zh:"紙"}
{en:"parent(s)",zh:"父(母)親"}
{en:"park",zh:"公園"}
{en:"part",zh:"部分"}
{en:"party",zh:"派對"}
{en:"pass",zh:"通過"}
{en:"past",zh:"經過"}
{en:"paste",zh:"黏貼,漿糊"}
{en:"pay",zh:"付錢"}
{en:"PE(physical education)",zh:"體育"}
{en:"peach",zh:"桃子"}
{en:"pear",zh:"梨子"}
{en:"pen",zh:"筆"}
{en:"pencil",zh:"鉛筆"}
{en:"people",zh:"人們,人民"}
{en:"perhaps",zh:"或許"}
{en:"person",zh:"人"}
{en:"pet",zh:"寵物"}
{en:"photo",zh:"相片"}
{en:"piano",zh:"鋼琴"}
{en:"pick",zh:"撿拾"}
{en:"picnic",zh:"野餐"}
{en:"picture",zh:"圖片,照片"}
{en:"pie",zh:"派"}
{en:"piece",zh:"片"}
{en:"pig",zh:"豬"}
{en:"pin",zh:"大頭針"}
{en:"pink",zh:"粉紅色(的)"}
{en:"pipe",zh:"管"}
{en:"pizza",zh:"披薩"}
{en:"place",zh:"地方"}
{en:"plan",zh:"計畫"}
{en:"planet",zh:"行星"}
{en:"plant",zh:"植物"}
{en:"plate",zh:"盤子"}
{en:"play",zh:"玩"}
{en:"player",zh:"球員,玩家"}
{en:"playground",zh:"操場"}
{en:"pleasure",zh:"樂趣,使高興"}
{en:"please",zh:"請"}
{en:"p.m.",zh:"下午"}
{en:"pocket",zh:"口袋"}
{en:"point",zh:"指著,得分"}
{en:"police",zh:"警察"}
{en:"polite",zh:"有禮貌的"}
{en:"pond",zh:"池塘"}
{en:"pool",zh:"游泳池"}
{en:"poor",zh:"貧困的,可憐的"}
{en:"popcorn",zh:"爆米花"}
{en:"popular",zh:"受歡迎的"}
{en:"pork",zh:"豬肉"}
{en:"possible",zh:"可能的"}
{en:"post office",zh:"郵局"}
{en:"postcard",zh:"明信片"}
{en:"pot",zh:"罐,壺,鍋子"}
{en:"pound",zh:"磅"}
{en:"practice",zh:"練習"}
{en:"pray",zh:"祈禱"}
{en:"prepare",zh:"準備"}
{en:"present",zh:"禮物"}
{en:"pretty",zh:"漂亮的,非常"}
{en:"price",zh:"價格"}
{en:"princess",zh:"公主"}
{en:"prize",zh:"獎品,獎金"}
{en:"problem",zh:"問題"}
{en:"program",zh:"節目"}
{en:"proud",zh:"驕傲的"}
{en:"public",zh:"公立的,公眾的"}
{en:"pull",zh:"拉"}
{en:"pumpkin",zh:"南瓜"}
{en:"purple",zh:"紫色的"}
{en:"push",zh:"推"}
{en:"put",zh:"放"}
{en:"quarter",zh:"15分鐘,1/4"}
{en:"queen",zh:"皇后"}
{en:"question",zh:"問題"}
{en:"quick",zh:"迅速的"}
{en:"quiet",zh:"安靜的"}
{en:"quite",zh:"相當"}
{en:"quiz",zh:"小考"}
{en:"rabbit",zh:"兔子"}
{en:"race",zh:"賽跑"}
{en:"radio",zh:"收音機"}
{en:"railroad",zh:"鐵路"}
{en:"rain",zh:"下雨"}
{en:"rainbow",zh:"彩虹"}
{en:"rainy",zh:"下雨的"}
{en:"raise",zh:"舉起,養育"}
{en:"rat",zh:"(大)老鼠,鼠輩"}
{en:"read",zh:"讀"}
{en:"ready",zh:"準備好的"}
{en:"real",zh:"真的"}
{en:"really",zh:"真地"}
{en:"recorder",zh:"錄音機"}
{en:"red",zh:"紅色(的)"}
{en:"refrigerator",zh:"冰箱"}
{en:"remember",zh:"記得"}
{en:"repeat",zh:"重複"}
{en:"reporter",zh:"記者"}
{en:"rest",zh:"休息"}
{en:"restaurant",zh:"餐館"}
{en:"restroom",zh:"洗手間"}
{en:"rice",zh:"米飯"}
{en:"rich",zh:"有錢的"}
{en:"ride",zh:"騎"}
{en:"right",zh:"右邊"}
{en:"ring",zh:"戒指"}
{en:"river",zh:"河"}
{en:"road",zh:"道路"}
{en:"robot",zh:"機器人"}
{en:"ROC",zh:"中華民國"}
{en:"rock",zh:"岩石"}
{en:"roll",zh:"滾"}
{en:"roller-skate",zh:"溜冰"}
{en:"room",zh:"房間"}
{en:"rope",zh:"繩子"}
{en:"rose",zh:"玫瑰"}
{en:"round",zh:"圓形的"}
{en:"row",zh:"劃(船)"}
{en:"rule",zh:"規則"}
{en:"ruler",zh:"尺"}
{en:"run",zh:"跑"}
{en:"sad",zh:"悲傷的"}
{en:"safe",zh:"安全的"}
{en:"sail",zh:"航行"}
{en:"salad",zh:"沙拉"}
{en:"sale",zh:"出售"}
{en:"salesman",zh:"推銷員"}
{en:"salt",zh:"鹽"}
{en:"same",zh:"相同的"}
{en:"sandwich",zh:"三明治"}
{en:"Saturday",zh:"星期六"}
{en:"sacred",zh:"神聖的"}
{en:"save",zh:"節省,挽救"}
{en:"say",zh:"說"}
{en:"school",zh:"學校"}
{en:"science",zh:"科學"}
{en:"scooter",zh:"速克達機車"}
{en:"screen",zh:"螢幕"}
{en:"sea",zh:"海"}
{en:"season",zh:"季節"}
{en:"seat",zh:"座位"}
{en:"second",zh:"第二(的)"}
{en:"secretary",zh:"秘書"}
{en:"see",zh:"看"}
{en:"seed",zh:"種子"}
{en:"seesaw",zh:"蹺蹺板"}
{en:"seldom",zh:"很少"}
{en:"sell",zh:"賣"}
{en:"send",zh:"寄"}
{en:"senior high school",zh:"高中"}
{en:"sentence",zh:"句子"}
{en:"September",zh:"九月"}
{en:"serious",zh:"嚴重的"}
{en:"(TV) set",zh:"(電視)機"}
{en:"seven",zh:"七"}
{en:"seventeen",zh:"十七"}
{en:"seventeenth",zh:"第十七(的)"}
{en:"seventh",zh:"第七(的)"}
{en:"seventy",zh:"七十"}
{en:"several",zh:"幾個的"}
{en:"shake",zh:"搖動"}
{en:"shall",zh:"將會,好嗎?"}
{en:"shape",zh:"形狀"}
{en:"share",zh:"分享"}
{en:"shark",zh:"鯊魚"}
{en:"she",zh:"她"}
{en:"sheep",zh:"綿羊"}
{en:"ship",zh:"船"}
{en:"shirt",zh:"襯衫"}
{en:"shoe(s)",zh:"鞋子"}
{en:"shop",zh:"商店"}
{en:"shopkeeper",zh:"店主"}
{en:"short",zh:"短的"}
{en:"shorts",zh:"短褲"}
{en:"should",zh:"應該"}
{en:"shoulder",zh:"肩膀"}
{en:"shout",zh:"喊叫"}
{en:"show",zh:"指示,表演"}
{en:"shy",zh:"害羞的"}
{en:"sick",zh:"生病的"}
{en:"side",zh:"旁邊,邊,面"}
{en:"sidewalk",zh:"人行道"}
{en:"sight",zh:"視力"}
{en:"sign",zh:"標誌"}
{en:"simple",zh:"簡單的"}
{en:"since",zh:"自從"}
{en:"sing",zh:"唱歌"}
{en:"singer",zh:"歌手"}
{en:"sir",zh:"先生"}
{en:"sister",zh:"姊妹"}
{en:"sit",zh:"坐"}
{en:"six",zh:"六"}
{en:"sixteen",zh:"十六"}
{en:"sixteenth",zh:"第十六(的〉"}
{en:"sixth",zh:"第六(的〉"}
{en:"sixty",zh:"六十"}
{en:"size",zh:"尺寸"}
{en:"skate",zh:"溜冰"}
{en:"skirt",zh:"裙子"}
{en:"sky",zh:"天空"}
{en:"sleep",zh:"睡覺"}
{en:"slide",zh:"滑坡,滑動"}
{en:"slim",zh:"苗條的"}
{en:"slow",zh:"慢的"}
{en:"small",zh:"小"}
{en:"smart",zh:"聰明的"}
{en:"smell",zh:"聞起來"}
{en:"smile",zh:"微笑"}
{en:"smoke",zh:"煙霧,抽菸"}
{en:"snack",zh:"點心"}
{en:"snake",zh:"蛇"}
{en:"snow",zh:"下雪"}
{en:"snowman",zh:"雪人"}
{en:"snowy",zh:"下雪的"}
{en:"so",zh:"如此地"}
{en:"soccer",zh:"足球"}
{en:"socks",zh:"襪子"}
{en:"sofa",zh:"沙發"}
{en:"soldier",zh:"軍人"}
{en:"some",zh:"一些"}
{en:"someone",zh:"某人"}
{en:"something",zh:"某事"}
{en:"sometimes",zh:"有時候"}
{en:"somewhere",zh:"某處"}
{en:"son",zh:"兒子"}
{en:"song",zh:"歌曲"}
{en:"soon",zh:"不久,即將"}
{en:"sore",zh:"疼痛的"}
{en:"sorry",zh:"抱歉"}
{en:"sound",zh:"聲音,聽起來"}
{en:"soup",zh:"湯"}
{en:"south",zh:"南方"}
{en:"space",zh:"空間"}
{en:"spaghetti",zh:"義大利麵"}
{en:"speak",zh:"說"}
{en:"special",zh:"特別的"}
{en:"spell",zh:"拼字"}
{en:"spend",zh:"花(錢,時間)"}
{en:"spider",zh:"蜘蛛"}
{en:"spoon",zh:"湯匙"}
{en:"sport",zh:"運動"}
{en:"spring",zh:"春天"}
{en:"square",zh:"正方形的"}
{en:"stairs",zh:"樓梯"}
{en:"stamp",zh:"郵票"}
{en:"stand",zh:"站立"}
{en:"star",zh:"星星"}
{en:"start",zh:"開始"}
{en:"station",zh:"車站,站,局"},
{en:"stay",zh:"停留"}
{en:"steak",zh:"(牛)排"}
{en:"still",zh:"仍然"}
{en:"stomach",zh:"胃"}
{en:"stop",zh:"停"}
{en:"store",zh:"商店"}
{en:"straight",zh:"直的"}
{en:"story",zh:"故事"}
{en:"strange",zh:"奇怪的"}
{en:"stranger",zh:"陌生人"}
{en:"strawberry",zh:"草莓"}
{en:"street",zh:"街道"}
{en:"strong",zh:"強壯的"}
{en:"student",zh:"學生"}
{en:"study",zh:"研讀,學習"}
{en:"stupid",zh:"笨的"}
{en:"subject",zh:"科目"}
{en:"successful",zh:"成功的"}
{en:"sugar",zh:"糖"}
{en:"summer",zh:"夏天"}
{en:"sun",zh:"太陽"}
{en:"Sunday",zh:"星期日"}
{en:"sunny",zh:"晴朗的"}
{en:"supermarket",zh:"超級市場"}
{en:"sure",zh:"確定的"}
{en:"surf",zh:"衝浪"}
{en:"surprise",zh:"使…驚訝"}
{en:"surprised",zh:"感到驚訝的"}
{en:"sweater",zh:"毛衣"}
{en:"sweet",zh:"甜的"}
{en:"swim",zh:"游泳"}
{en:"swing",zh:"鞦韆,搖擺"}
{en:"table",zh:"桌子"}
{en:"tail",zh:"尾巴"}
{en:"Taiwan",zh:"臺灣"}
{en:"take",zh:"拿"}
{en:"talk",zh:"說話"}
{en:"tall",zh:"高的"}
{en:"tape",zh:"錄音帶"}
{en:"taste",zh:"品嚐"}
{en:"taxi",zh:"計程車"}
{en:"tea",zh:"茶"}
{en:"teach",zh:"教導"}
{en:"teacher",zh:"教師"}
{en:"team",zh:"團隊"}
{en:"teenager",zh:"青少年"}
{en:"telephone",zh:"電話"}
{en:"television",zh:"電視"}
{en:"tell",zh:"告訴"}
{en:"temple",zh:"寺廟"}
{en:"ten",zh:"十"}
{en:"tennis",zh:"網球"}
{en:"tenth",zh:"第十〈的〉"}
{en:"terrible",zh:"可怕的"}
{en:"test",zh:"考試,測試"}
{en:"than",zh:"比…"}
{en:"thank",zh:"謝謝"}
{en:"that",zh:"那個"}
{en:"the",zh:"這/那"}
{en:"theater",zh:"戲院"}
{en:"then",zh:"那時"}
{en:"there",zh:"那裡"}
{en:"these",zh:"這些"}
{en:"they",zh:"他們"}
{en:"thick",zh:"厚的"}
{en:"thin",zh:"瘦的"}
{en:"thing",zh:"事情"}
{en:"think",zh:"想,思考"}
{en:"third",zh:"第三〈的〉"}
{en:"thirsty",zh:"口渴的"}
{en:"thirteen",zh:"十三"}
{en:"thirteenth",zh:"第十三"}
{en:"thirty",zh:"三十"}
{en:"this",zh:"這個"}
{en:"throat",zh:"喉嚨"}
{en:"throw",zh:"丟"}
{en:"those",zh:"那些"}
{en:"though",zh:"雖然"}
{en:"thousand",zh:"千"}
{en:"three",zh:"三"}
{en:"Thursday",zh:"星期四"}
{en:"ticket",zh:"票券"}
{en:"tidy",zh:"整潔的"}
{en:"tiger",zh:"老虎"}
{en:"tie",zh:"領帶,捆,繫"}
{en:"time",zh:"時間"}
{en:"tired",zh:"疲倦的"}
{en:"to",zh:"到"}
{en:"toast",zh:"土司,烘烤"}
{en:"today",zh:"今天"}
{en:"toe",zh:"腳趾"}
{en:"together",zh:"一起"}
{en:"tomato",zh:"番茄"}
{en:"tomorrow",zh:"明天"}
{en:"tonight",zh:"今晚"}
{en:"too",zh:"也,太..."}
{en:"tooth",zh:"牙齒"}
{en:"top",zh:"頂端"}
{en:"total",zh:"總計"}
{en:"touch",zh:"碰觸"}
{en:"towel",zh:"毛巾"}
{en:"town",zh:"城鎮"}
{en:"toy",zh:"玩具"}
{en:"traffic",zh:"交通"}
{en:"train",zh:"火車"}
{en:"trash",zh:"垃圾"}
{en:"treat",zh:"請客,對待"}
{en:"tree",zh:"樹"}
{en:"trick",zh:"惡作劇"}
{en:"trip",zh:"(短程)旅行"}
{en:"trouble",zh:"麻煩"}
{en:"truck",zh:"卡車"}
{en:"true",zh:"真實的"}
{en:"try",zh:"嘗試"}
{en:"T-shirt",zh:"T 恤"}
{en:"tub",zh:"浴缸,洗澡"}
{en:"Tuesday",zh:"星期二"}
{en:"turkey",zh:"火雞"}
{en:"turn",zh:"轉動,轉彎"}
{en:"turtle",zh:"烏龜"}
{en:"twelfth",zh:"第十二(的)"}
{en:"twelve",zh:"十二"}
{en:"twenty",zh:"二十"}
{en:"twentieth",zh:"第二十(的)"}
{en:"twice",zh:"兩次"}
{en:"two",zh:"二"}
{en:"type",zh:"打字"}
{en:"typhoon",zh:"颱風"}
{en:"umbrella",zh:"雨傘"}
{en:"uncle",zh:"伯(叔)"}
{en:"under",zh:"在…之下"}
{en:"understand",zh:"了解"}
{en:"unhappy",zh:"不快樂的"}
{en:"uniform",zh:"制服"}
{en:"until",zh:"直到"}
{en:"up",zh:"向上"}
{en:"USA",zh:"美國"}
{en:"use",zh:"使用"}
{en:"useful",zh:"有用的"}
{en:"usually",zh:"通常"}
{en:"vacation",zh:"假期"}
{en:"vegetable",zh:"蔬菜"}
{en:"very",zh:"非常"}
{en:"vest",zh:"背心"}
{en:"video",zh:"錄影帶"}
{en:"violin",zh:"小提琴"}
{en:"visit",zh:"參觀"}
{en:"voice",zh:"聲音"}
{en:"wait",zh:"等待"}
{en:"waiter",zh:"男服務生"}
{en:"waitress",zh:"女服務生"}
{en:"wake",zh:"醒來"}
{en:"walk",zh:"走路"}
{en:"wall",zh:"牆壁"}
{en:"wallet",zh:"皮夾"}
{en:"want",zh:"想要"}
{en:"warm",zh:"溫暖的"}
{en:"wash",zh:"清洗"}
{en:"watch",zh:"看"}
{en:"water",zh:"水"}
{en:"watermelon",zh:"西瓜"}
{en:"wave",zh:"波浪"}
{en:"way",zh:"道路,方法"}
{en:"we",zh:"我們"}
{en:"weak",zh:"弱的"}
{en:"wear",zh:"穿"}
{en:"weather",zh:"天氣"}
{en:"Wednesday",zh:"星期三"}
{en:"week",zh:"星期"}
{en:"weekend",zh:"週末"}
{en:"welcome",zh:"受歡迎的"}
{en:"well",zh:"好地"}
{en:"west",zh:"西方"}
{en:"wet",zh:"濕的"}
{en:"whale",zh:"鯨魚"}
{en:"what",zh:"什麼"}
{en:"when",zh:"何時"}
{en:"where",zh:"何處"}
{en:"whether",zh:"是否"}
{en:"which",zh:"哪一個"}
{en:"white",zh:"白色(的)"}
{en:"who",zh:"誰"}
{en:"whose",zh:"誰的"}
{en:"why",zh:"為什麼"}
{en:"wife",zh:"妻子"}
{en:"will",zh:"將會..."}
{en:"win",赢}
{en:"wind",zh:"風"}
{en:"window",zh:"窗戶"}
{en:"windy",zh:"多風的"}
{en:"winter",zh:"冬天"}
{en:"wise",zh:"明智的"}
{en:"wish",zh:"祝福…"}
{en:"with",zh:"和"}
{en:"without",zh:"沒有"}
{en:"woman",zh:"女人"}
{en:"wonderful",zh:"極好的"}
{en:"word",zh:"字"}
{en:"work",zh:"工作"}
{en:"workbook",zh:"作業本"}
{en:"worker",zh:"工人"}
{en:"world",zh:"世界"}
{en:"worry",zh:"擔心"}
{en:"write",zh:"寫"}
{en:"writer",zh:"作家"}
{en:"wrong",zh:"錯誤的"}
{en:"yard",zh:"庭院"}
{en:"year",zh:"年"}
{en:"yellow",zh:"黃色(的)"}
{en:"yes",zh:"是"}
{en:"yesterday",zh:"昨天"}
{en:"yet",zh:"尚未"}
{en:"you",zh:"你(們)"}
{en:"young",zh:"年輕的"}
{en:"yummy",zh:"好吃的"}
{en:"zebra",zh:"斑馬"}
{en:"zero",zh:"零"}
{en:"zoo",zh:"動物園"}
];

const juniorWords = [
{en:"important",zh:"重要的"},
{en:"decide",zh:"決定"},
{en:"improve",zh:"改善"},
{en:"practice",zh:"練習"},
{en:"discover",zh:"發現"},
{en:"knowledge",zh:"知識"},
{en:"develop",zh:"發展"},
{en:"environment",zh:"環境"},
{en:"culture",zh:"文化"},
{en:"technology",zh:"科技"},
{en:"experience",zh:"經驗"},
{en:"opinion",zh:"意見"},
{en:"relationship",zh:"關係"},
{en:"responsibility",zh:"責任"},
{en:"education",zh:"教育"},
{en:"communication",zh:"溝通"},
{en:"information",zh:"資訊"},
{en:"situation",zh:"情況"},
{en:"difference",zh:"差異"},
{en:"example",zh:"例子"}
];


